apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
  namespace: sampleapp
  labels:
    app: sampleapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
        - name: sampleapp
          image: 669443521868.dkr.ecr.ap-south-1.amazonaws.com/sampleapp:10
   # we'll update this from Jenkins
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
